In [16]:
import pandas as pd
from datetime import datetime

# 1. Load the Excel file
file_path = r"C:\Users\haris\Downloads\Untitled spreadsheet.xlsx"
df = pd.read_excel(file_path)

# 2. Identify and handle missing values
print("Missing values before cleaning:")
print(df.isnull().sum())

# Fill numerical missing values with median
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Fill categorical missing values with mode
cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

# 3. Remove duplicate rows
print(f"\nFound {df.duplicated().sum()} duplicates")
df = df.drop_duplicates()

# 4. Standardize text values
# Example for gender standardization
if 'gender' in df.columns:
    df['gender'] = df['gender'].str.upper().str.strip()
    gender_mapping = {'M': 'MALE', 'F': 'FEMALE', 'MALE': 'MALE', 'FEMALE': 'FEMALE'}
    df['gender'] = df['gender'].map(gender_mapping).fillna(df['gender'])

# Standardize other text columns (example for country names)
text_cols = df.select_dtypes(include=['object']).columns
for col in text_cols:
    if col != 'gender':  # Skip gender if already standardized
        df[col] = df[col].str.title().str.strip()  # Converts to Title Case

# 5. Convert date formats
date_cols = df.select_dtypes(include=['object']).filter(regex='date|Date|DATE').columns
for col in date_cols:
    try:
        df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce').dt.strftime('%d-%m-%Y')
    except:
        pass

# 6. Clean column headers
df.columns = (df.columns.str.strip()
              .str.lower()
              .str.replace(' ', '_')
              .str.replace('[^a-z0-9_]', ''))

# 7. Fix data types
# Convert age-like columns to integers
age_cols = [col for col in df.columns if 'age' in col.lower()]
for col in age_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

# Convert date columns to datetime
date_cols = df.select_dtypes(include=['object']).filter(regex='date').columns
for col in date_cols:
    df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')

# 8. Final verification
print("\nData after cleaning:")
print(df.info())
print("\nMissing values after cleaning:")
print(df.isnull().sum())
print("\nSample of cleaned data:")
print(df.head())

# 9. Save cleaned data to new Excel file
cleaned_file_path = r"C:\Users\haris\Downloads\Cleaned_spreadsheet.xlsx"
df.to_excel(cleaned_file_path, index=False)
print(f"\nCleaned data saved to: {cleaned_file_path}")

Missing values before cleaning:
ID                      0
Year_Birth              0
Education               6
Marital_Status          7
Income                 27
Kidhome                 2
Teenhome                1
Dt_Customer             3
Recency                 1
MntWines                2
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

Found 0 duplicates

Data after cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2240 non-null   int64
 1   year_birth           2240 non-null   int64
 2   education            2240 non-null   object
 3   marital_status       2240 non-null   object
 4   income               2240 non-null   float64
 5   kidhome              2240 non-null   float64
 6   teenhome             2240 non-null   float64
 7   dt_customer          2237 non-null   datetime64[ns]
 8   recency              2240 non-null   float64
 9   mntwines             2240 non-null   float64
 10  mntfruits            2240 non-null   int64
 11  mntmeatproducts      2240 non-null   int64
 12  mntfishproducts      2240 non-null   int64
 13  mntsweetproducts     2240 non-null   int64
 14  mntgoldprods         2240 non-null   int64
 15  numdealspurchases    2240 non-null   int64
 16  numwebpurchases      2240 non-null   int64
 17  numcatalogpurchases  2240 non-null   int64
 18  numstorepurchases    2240 non-null   int64
 19  numwebvisitsmonth    2240 non-null   int64
 20  acceptedcmp3         2240 non-null   int64
 21  acceptedcmp4         2240 non-null   int64
 22  acceptedcmp5         2240 non-null   int64
 23  acceptedcmp1         2240 non-null   int64
 24  acceptedcmp2         2240 non-null   int64
 25  complain             2240 non-null   int64
 26  z_costcontact        2240 non-null   int64
 27  z_revenue            2240 non-null   int64
 28  response             2240 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(21), object(2)
memory usage: 507.6+ KB
None

Missing values after cleaning:
id                     0
year_birth             0
education              0
marital_status         0
income                 0
kidhome                0
teenhome               0
dt_customer            3
recency                0
mntwines               0
mntfruits              0
mntmeatproducts        0
mntfishproducts        0
mntsweetproducts       0
mntgoldprods           0
numdealspurchases      0
numwebpurchases        0
numcatalogpurchases    0
numstorepurchases      0
numwebvisitsmonth      0
acceptedcmp3           0
acceptedcmp4           0
acceptedcmp5           0
acceptedcmp1           0
acceptedcmp2           0
complain               0
z_costcontact          0
z_revenue              0
response               0
dtype: int64

Sample of cleaned data:
     id  year_birth   education marital_status   income  kidhome  teenhome  \
0  5524        1957  Graduation         Single  58138.0      0.0       0.0
1  2174        1954  Graduation         Single  46344.0      1.0       1.0
2  4141        1965  Graduation       Together  71613.0      0.0       0.0
3  6182        1984  Graduation       Together  26646.0      1.0       0.0
4  5324        1981         Phd        Married  58293.0      1.0       0.0

  dt_customer  recency  mntwines  mntfruits  mntmeatproducts  mntfishproducts  \
0  2012-09-04     58.0     635.0         88              546              172
1  2014-03-08     38.0      11.0          1                6                2
2  2013-08-21     26.0     426.0         49              127              111
3  2014-02-10     26.0      11.0          4               20               10
4  2014-01-19     94.0     173.0         43              118               46

   mntsweetproducts  mntgoldprods  numdealspurchases  numwebpurchases  \
0                88            88                  3                8
1                 1             6                  2                1
2                21            42                  1                8
3                 3             5                  2                2
4                27            15                  5                5

   numcatalogpurchases  numstorepurchases  numwebvisitsmonth  acceptedcmp3  \
0                   10                  4                  7             0
1                    1                  2                  5             0
2                    2                 10                  4             0
3                    0                  4                  6             0
4                    3                  6                  5             0

   acceptedcmp4  acceptedcmp5  acceptedcmp1  acceptedcmp2  complain  \
0             0             0             0             0         0
1             0             0             0             0         0
2             0             0             0             0         0
3             0             0             0             0         0
4             0             0             0             0         0

   z_costcontact  z_revenue  response
0              3         11         1
1              3         11         0
2              3         11         0
3              3         11         0
4              3         11         0

Cleaned data saved to: C:\Users\haris\Downloads\Cleaned_spreadsheet.xlsx